[package]
name = "mabi-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
gilrs = "0.10.8"
pwm-pca9685 = "1.0.0"
serde = { version = "1.0.215", features = ["derive"] }
toml-cfg = "0.2.0"
